### ISSUE TITLE
react-native init Hello  编译错误

### ISSUE THREAD

**Issue by simpledong81** [vczero/React-Native-Code#1]
升级到node5.4，npm3
安装了react-native后
结果init Hello出来的iOS工程编译出现下面错误，能告知一下原因吗？
- react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/xx/Library/Developer/Xcode/DerivedData/Hello-fzjwasoudwwrkufpmhnvtgvoesyi/Build/Products/Debug-iphonesimulator/Hello.app/main.jsbundle --assets-dest /Users/dongyihao/Library/Developer/Xcode/DerivedData/Hello-fzjwasoudwwrkufpmhnvtgvoesyi/Build/Products/Debug-iphonesimulator/Hello.app
  bundle: Created ReactPackager
  uncaught error Error: TypeError: Cannot read property 'error' of null
  at index.js:117:20
  at tryCallOne (/Users/xx/Desktop/dongyh/react-native/Hello/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
  at /Users/xx/Desktop/dongyh/react-native/Hello/node_modules/react-native/node_modules/promise/lib/core.js:123:15
  at flush (/Users/xx/Desktop/dongyh/react-native/Hello/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
  at nextTickCallbackWith0Args (node.js:456:9)
  TransformError: /Users/xx/Desktop/dongyh/react-native/Hello/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/lib/index.js: Cannot read property 'error' of null
  See logs /var/folders/zj/h20kmmsd60vdpxlf0f0d7l9w0000gn/T/react-packager.log
  at SocketClient._handleMessage (SocketClient.js:139:23)
  at BunserBuf.<anonymous> (SocketClient.js:53:42)
  at emitOne (events.js:77:13)
  at BunserBuf.emit (events.js:169:7)
  at BunserBuf.process (/Users/xx/Desktop/dongyh/react-native/Hello/node_modules/react-native/node_modules/bser/index.js:289:10)
  at /Users/xx/Desktop/dongyh/react-native/Hello/node_modules/react-native/node_modules/bser/index.js:244:12
  at nextTickCallbackWith0Args (node.js:456:9)
  at process._tickCallback (node.js:385:13)
  Command /bin/sh failed with exit code 1

**Comment by vczero** [comment]
确保升级下watchman, 如果之前没有安装则不用升级。
可以参考这个：https://github.com/facebook/react-native/issues/5221 
以下是成功状态：

```
mobile$ npm -v
3.3.12
mobile$ node -v
v5.3.0
$ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output ./test.bundle
bundle: Created ReactPackager
bundle: start
bundle: finish
bundle: Writing bundle output to: ./test.bundle
bundle: Closing client
Assets destination folder is not set, skipping...
bundle: Done writing bundle output
```

**Comment by simpledong81** [comment]
多谢回复。
我之前已经是按照#5221升级的watchman，但是效果也一样
npm3的话react-native init会一直处于等待状态，然后降到npm2，但是就出现了我汇报的问题
react-native-cli: 0.1.9
react-native: 0.18.0-rc
npm: 3.5.3
node: v5.4.0

**Comment by vczero** [comment]
react-native init会一直处于等待状态？  
可以修改npm源为国内镜像，例如淘宝的cnpm

**Comment by simpledong81** [comment]
早就修改过镜像了的
不知道是不是react-native的问题

**Comment by simpledong81** [comment]
我把
  "dependencies": {
    "react-native": "^0.18.0-rc"
  }
中的react-native版本降到0.17.0就OK了
