### ISSUE TITLE
第七章的热更新导入build报错，提示找不到RCTBridge.h

### ISSUE THREAD

**Issue by JRJian** [vczero/React-Native-Code#5]
![错误](https://cloud.githubusercontent.com/assets/8022148/13627417/53697c8a-e605-11e5-98a8-b38419a36dc3.png)
我先是用Swift嵌入了React的几个框架之后，正常能运行App。
接着我想实现热更新，于是导入了ReactVersion库后提示上面的错误，不知如何解决这个问题
![目录结构](https://cloud.githubusercontent.com/assets/8022148/13627479/931fb79a-e605-11e5-9890-c5a398ad6c70.png)

**Comment by JRJian** [comment]
解决了！需要在ReactVersion->target->build setting 设置React 的 Header Search Path

**Comment by vczero** [comment]
对的这个编译必须步骤

**Comment by JRJian** [comment]
工程已经有些旧了，rejecter方法 RN0.21已经改成typedef void (^RCTPromiseRejectBlock)(NSString *code, NSString *message, NSError *error);需要传入3个参数！
self.bridge.bundleURL 赋值报错，因为@property (nonatomic, weak, readonly) RCTBridge *bridge;已经改成只读。。
我已经在工程里将#import "RCTBridge.h"改成#import "RCTBridge+Private.h"解决了这个问题。

**Comment by vczero** [comment]
@JRJian 请帮忙提交个pull request，我合进代码

**Comment by JRJian** [comment]
好的。

**Comment by vczero** [comment]
@JRJian 多谢啦

**Comment by JRJian** [comment]
@vczero 已提交

**Comment by vczero** [comment]
@JRJian 验证完，立即合并，十分感谢
