### ISSUE TITLE
书刚买到手里就过时了

### ISSUE THREAD

**Issue by ghost** [vczero/React-Native-Code#8]
现在RN和书里已经完全不一样了，代码能不能更新下？

**Comment by slcoco** [comment]
我也是,好多都不可以使用了

**Comment by vczero** [comment]
@z306007236 @slcoco 这个项目是最新代码，可以参考下：https://github.com/vczero/toilet。

**Comment by happyliuzh** [comment]
示例代码跑不起来，能否给出解决方案，否则看着书学没什么用啊？

**Comment by vczero** [comment]
@happyliuzh 推荐结合这门课程看：http://coding.imooc.com/class/69.html，里面都是ES6语法。技术的确更新太快了。不过又要让你破费了，实在抱歉～

**Comment by happyliuzh** [comment]
大神，这个要128大洋啊。购书的能否优惠一些。

**Comment by vczero** [comment]
@happyliuzh 加我微信 vczero
